<script src="./add-budget-expense.ts" lang="ts"></script>
<style src="./add-budget-expense.scss" lang="scss" scoped></style>

<template>
	<v-dialog
		class="dialog add-expense"
		v-model="showDialog"
		max-width="800px">
		<v-card>
			<v-card-title class="dialog--title">
				<span v-if="!editMode">Add Expense to Budget</span>
				<span v-if="editMode">Update Expense</span>
			</v-card-title>

			<v-card-text>
				<v-form ref="expenseForm" v-model="expenseValid">
					<v-select
						@change="updateSelectedType()"
						v-model="form.type.value"
						:rules="form.type.rules"
						:items="billTypes"
						item-value="id"
						item-text="name"
						label="Select Expense Type"></v-select>

					<Bank
						v-if="showTypeForm('banks')"
						:data="currentData"
						:dialog="showDialog"
						@submitForm="submitAndCloseDialog($event)"></Bank>
					<CommonExpense
						v-if="showTypeForm('childcare')"
						type="childcare"
						:data="currentData"
						:dialog="showDialog"
						:cycle="cycle"
						:showPaidForm="showPaidForm"
						@submitForm="submitAndCloseDialog($event)"></CommonExpense>
					<CreditCard
						v-if="showTypeForm('credit-cards')"
						:data="currentData"
						:dialog="showDialog"
						:cycle="cycle"
						:showPaidForm="showPaidForm"
						@submitForm="submitAndCloseDialog($event)"></CreditCard>
					<CommonExpense
						v-if="showTypeForm('education')"
						type="education"
						:data="currentData"
						:dialog="showDialog"
						:cycle="cycle"
						:showPaidForm="showPaidForm"
						@submitForm="submitAndCloseDialog($event)"></CommonExpense>
					<CommonExpense
						v-if="showTypeForm('entertainment')"
						type="entertainment"
						:data="currentData"
						:dialog="showDialog"
						:cycle="cycle"
						:showPaidForm="showPaidForm"
						@submitForm="submitAndCloseDialog($event)"></CommonExpense>
					<CommonExpense
						v-if="showTypeForm('food')"
						type="food"
						:data="currentData"
						:dialog="showDialog"
						:cycle="cycle"
						:showPaidForm="showPaidForm"
						@submitForm="submitAndCloseDialog($event)"></CommonExpense>
					<CommonExpense
						v-if="showTypeForm('gift')"
						type="gift"
						:data="currentData"
						:dialog="showDialog"
						:cycle="cycle"
						:showPaidForm="showPaidForm"
						@submitForm="submitAndCloseDialog($event)"></CommonExpense>
					<CommonExpense
						v-if="showTypeForm('housing')"
						type="housing"
						:data="currentData"
						:dialog="showDialog"
						:cycle="cycle"
						:showPaidForm="showPaidForm"
						@submitForm="submitAndCloseDialog($event)"></CommonExpense>
					<Investment
						v-if="showTypeForm('investments')"
						:data="currentData"
						:dialog="showDialog"
						@submitForm="submitAndCloseDialog($event)"></Investment>
					<Job
						v-if="showTypeForm('incomes')"
						:data="currentData"
						:dialog="showDialog"
						@submitForm="submitAndCloseDialog($event)"></Job>
					<CommonExpense
						v-if="showTypeForm('loan')"
						type="loan"
						:data="currentData"
						:dialog="showDialog"
						:cycle="cycle"
						:showPaidForm="showPaidForm"
						@submitForm="submitAndCloseDialog($event)"></CommonExpense>
					<CommonExpense
						v-if="showTypeForm('medical')"
						type="medical"
						:data="currentData"
						:dialog="showDialog"
						:cycle="cycle"
						:showPaidForm="showPaidForm"
						@submitForm="submitAndCloseDialog($event)"></CommonExpense>
					<Misc
						v-if="showTypeForm('miscellaneous')"
						:data="currentData"
						:dialog="showDialog"
						:cycle="cycle"
						:showPaidForm="showPaidForm"
						@submitForm="submitAndCloseDialog($event)"></Misc>
					<CommonExpense
						v-if="showTypeForm('personal')"
						type="personal"
						:data="currentData"
						:dialog="showDialog"
						:cycle="cycle"
						:showPaidForm="showPaidForm"
						@submitForm="submitAndCloseDialog($event)"></CommonExpense>
					<CommonExpense
						v-if="showTypeForm('shopping')"
						type="shopping"
						:data="currentData"
						:dialog="showDialog"
						:cycle="cycle"
						:showPaidForm="showPaidForm"
						@submitForm="submitAndCloseDialog($event)"></CommonExpense>
					<CommonExpense
						v-if="showTypeForm('subscription')"
						type="subscription"
						:data="currentData"
						:dialog="showDialog"
						:cycle="cycle"
						:showPaidForm="showPaidForm"
						@submitForm="submitAndCloseDialog($event)"></CommonExpense>
					<CommonExpense
						v-if="showTypeForm('tax')"
						type="tax"
						:data="currentData"
						:dialog="showDialog"
						:cycle="cycle"
						:showPaidForm="showPaidForm"
						@submitForm="submitAndCloseDialog($event)"></CommonExpense>
					<CommonExpense
						v-if="showTypeForm('travel')"
						type="travel"
						:data="currentData"
						:dialog="showDialog"
						:cycle="cycle"
						:showPaidForm="showPaidForm"
						@submitForm="submitAndCloseDialog($event)"></CommonExpense>
					<Utility
						v-if="showTypeForm('utilities')"
						:data="currentData"
						:dialog="showDialog"
						:cycle="cycle"
						:showPaidForm="showPaidForm"
						@submitForm="submitAndCloseDialog($event)"></Utility>
					<Vehicle
						v-if="showTypeForm('vehicles')"
						:data="currentData"
						:dialog="showDialog"
						:cycle="cycle"
						:showPaidForm="showPaidForm"
						@submitForm="submitAndCloseDialog($event)"></Vehicle>
				</v-form>
			</v-card-text>
		</v-card>
	</v-dialog>
</template>
